### ISSUE TITLE
Error occur during circmimi_tools interactions command

### ISSUE THREAD

**Issue by aman21392** [TreesLab/CircMiMi#4]
I used this command:-
nohup circmimi_tools interactions -r /Drive1/interactome_circRNA_miRNA_mRNA/ -i /Drive1/interactome_circRNA_miRNA_mRNA/checking_circRNA/E6_coordinate.tsv -o circ_interactome -p 30 &

The error which I got is below:

Traceback (most recent call last):
  File "/home/aclab/.local/bin/circmimi_tools", line 8, in <module>
    sys.exit(cli())
  File "/home/aclab/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/aclab/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/aclab/.local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aclab/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aclab/.local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/aclab/.local/lib/python3.7/site-packages/circmimi/scripts/circmimi_tools.py", line 109, in predict_interactions
    circmimi_result.run(circ_file)
  File "/home/aclab/.local/lib/python3.7/site-packages/circmimi/circmimi.py", line 197, in run
    'name'
  File "/home/aclab/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 7641, in groupby
    dropna=dropna,
  File "/home/aclab/.local/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 897, in __init__
    dropna=self.dropna,
  File "/home/aclab/.local/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 852, in get_grouper
    obj._check_label_or_level_ambiguity(gpr, axis=axis)
  File "/home/aclab/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 1733, in _check_label_or_level_ambiguity
    raise ValueError(msg)
ValueError: 'name' is both an index level and a column label, which is ambiguous.

can you please solve this issues. Thanks in advance.

**Comment by chiangtw** [comment]
Hi,

Thanks for reporting!
Could you provide the version of your installed pandas? It would be very helpful!

tw

**Comment by aman21392** [comment]
Thanks for your reply.

**When i use pip command : pip show pandas then it shows
Name: pandas
Version: 1.3.5
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: /home/aclab/.local/lib/python3.7/site-packages
Requires: numpy, python-dateutil, pytz
Required-by: circmimi, statsmodels**

**For python 3.6.9  the pandas version is 1.1.5. 
Python 3.6.9 is the default setting.**

Thanks in advance
